version: '3.8'

services:
  consul:
    image: consul:1.15
    ports:
      - "8500:8500"   # Web UI
      - "8600:8600/udp"  # DNS
    command: agent -server -bootstrap -ui -client=0.0.0.0

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: simplebank_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: