services:
  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - consul_data:/consul/data
      - ./backups:/consul/backups
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    user: "0:0"
    command: >
      sh -c "
      consul agent -dev -client=0.0.0.0 -ui &
      sleep 15 &&
      BACKUP_FILE=$$(ls -t /consul/backups/*.snap 2>/dev/null | head -n1) &&
      if [ -n \"$$BACKUP_FILE\" ]; then
        echo \"Найден snapshot: $$BACKUP_FILE\" &&
        until consul members 2>/dev/null; do sleep 2; done &&
        consul snapshot restore \"$$BACKUP_FILE\" &&
        echo \"Snapshot восстановлен успешно!\"
      else
        echo \"Snapshot файлы не найдены\"
      fi &&
      wait
      "
    restart: unless-stopped
    networks:
      - simplebank-net

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: simplebank_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - simplebank-net

  # Микросервисы
  auth-server:
    build:
      context: .
      dockerfile: auth-server/Dockerfile
    container_name: auth-server
    ports:
      - "9000:9000"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/simplebank_db
      - GATEWAY_URL=http://gateway:8081
      - AUTH_SERVER_URL=http://auth-server:9000
    depends_on:
      - postgres
      - consul
    restart: unless-stopped
    networks:
      - simplebank-net

  accounts:
    build:
      context: .
      dockerfile: accounts/Dockerfile
    container_name: accounts
    ports:
      - "8082:8082"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/simplebank_db
      - GATEWAY_URL=http://gateway:8081
      - AUTH_SERVER_URL=http://auth-server:9000
    depends_on:
      - postgres
      - consul
      - auth-server
    restart: unless-stopped
    networks:
      - simplebank-net

  cash:
    build:
      context: .
      dockerfile: cash/Dockerfile
    container_name: cash
    ports:
      - "8083:8083"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/simplebank_db
      - GATEWAY_URL=http://gateway:8081
      - AUTH_SERVER_URL=http://auth-server:9000
    depends_on:
      - postgres
      - consul
      - auth-server
    restart: unless-stopped
    networks:
      - simplebank-net

  transfer:
    build:
      context: .
      dockerfile: transfer/Dockerfile
    container_name: transfer
    ports:
      - "8084:8084"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/simplebank_db
      - GATEWAY_URL=http://gateway:8081
      - AUTH_SERVER_URL=http://auth-server:9000
    depends_on:
      - postgres
      - consul
      - auth-server
    restart: unless-stopped
    networks:
      - simplebank-net

  exchange:
    build:
      context: .
      dockerfile: exchange/Dockerfile
    container_name: exchange
    ports:
      - "8086:8086"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/simplebank_db
      - GATEWAY_URL=http://gateway:8081
      - AUTH_SERVER_URL=http://auth-server:9000
    depends_on:
      - postgres
      - consul
      - auth-server
    restart: unless-stopped
    networks:
      - simplebank-net

  exchange-generator:
    build:
      context: .
      dockerfile: exchange-generator/Dockerfile
    container_name: exchange-generator
    ports:
      - "8085:8085"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/simplebank_db
      - GATEWAY_URL=http://gateway:8081
      - AUTH_SERVER_URL=http://auth-server:9000
    depends_on:
      - consul
      - auth-server
      - gateway
    restart: unless-stopped
    networks:
      - simplebank-net

  blocker:
    build:
      context: .
      dockerfile: blocker/Dockerfile
    container_name: blocker
    ports:
      - "8087:8087"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/simplebank_db
      - GATEWAY_URL=http://gateway:8081
      - AUTH_SERVER_URL=http://auth-server:9000
    depends_on:
      - consul
      - auth-server
    restart: unless-stopped
    networks:
      - simplebank-net

  notifications:
    build:
      context: .
      dockerfile: notifications/Dockerfile
    container_name: notifications
    ports:
      - "8088:8088"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/simplebank_db
      - GATEWAY_URL=http://gateway:8081
      - AUTH_SERVER_URL=http://auth-server:9000
    depends_on:
      - postgres
      - consul
      - auth-server
    restart: unless-stopped
    networks:
      - simplebank-net

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway
    ports:
      - "8081:8081"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/simplebank_db
      - GATEWAY_URL=http://gateway:8081
      - AUTH_SERVER_URL=http://auth-server:9000
    depends_on:
      - consul
    restart: unless-stopped
    networks:
      - simplebank-net

  front-ui:
    build:
      context: .
      dockerfile: front-ui/Dockerfile
    container_name: front-ui
    ports:
      - "8080:8080"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/simplebank_db
      - GATEWAY_URL=http://gateway:8081
      - AUTH_SERVER_URL=http://auth-server:9000
    depends_on:
      - consul
      - gateway
    restart: unless-stopped
    networks:
      - simplebank-net

networks:
  simplebank-net:
    driver: bridge

volumes:
  postgres_data:
  consul_data: