apiVersion: v2
name: simplebank
description: A Helm umbrella chart for SimpleBank microservices application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "15.5.32"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: accounts
    version: "0.1.0"
    repository: "file://../accounts"
    condition: accounts.enabled
  - name: cash
    version: "0.1.0"
    repository: "file://../cash"
    condition: cash.enabled
  - name: exchange
    version: "0.1.0"
    repository: "file://../exchange"
    condition: exchange.enabled
  - name: transfer
    version: "0.1.0"
    repository: "file://../transfer"
    condition: transfer.enabled
  - name: notifications
    version: "0.1.0"
    repository: "file://../notifications"
    condition: notifications.enabled
  - name: gateway
    version: "0.1.0"
    repository: "file://../gateway"
    condition: gateway.enabled
  - name: authServer
    version: "0.1.0"
    repository: "file://../auth-server"
    condition: authServer.enabled
  - name: frontUi
    version: "0.1.0"
    repository: "file://../front-ui"
    condition: frontUi.enabled
