# Global configuration
global:
  imageRegistry: ""
  imagePullSecrets: []

# PostgreSQL configuration
postgresql:
  enabled: true
  auth:
    postgresPassword: "postgres"
    username: "postgres"
    password: "postgres"
    database: "simplebank_db"
  primary:
    persistence:
      enabled: true
      size: 8Gi

# Microservices configuration
accounts:
  enabled: true
  service:
    port: 8082
  database:
    url: "jdbc:postgresql://simplebank-postgresql:5432/simplebank_db"

cash:
  enabled: true
  service:
    port: 8083
  database:
    url: "jdbc:postgresql://simplebank-postgresql:5432/simplebank_db"

exchange:
  enabled: true
  service:
    port: 8086
  database:
    url: "jdbc:postgresql://simplebank-postgresql:5432/simplebank_db"

transfer:
  enabled: true
  service:
    port: 8084
  database:
    url: "jdbc:postgresql://simplebank-postgresql:5432/simplebank_db"

gateway:
  enabled: true
  service:
    port: 8081

authServer:
  enabled: true
  service:
    port: 9000
  database:
    url: "jdbc:postgresql://simplebank-postgresql:5432/simplebank_db"

frontUi:
  enabled: true
  service:
    port: 8080
