apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blocker.fullname" . }}-secret
  labels:
    {{- include "blocker.labels" . | nindent 4 }}
type: Opaque
data:
  oauth2-client-secret: {{ .Values.oauth2.clientSecret | b64enc }}
