apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-config
  namespace: simplebank
data:
  application.properties: |
    # Настройки сервера
    server.port=8082
    
    # Actuator configuration
    management.endpoints.web.exposure.include=health,info
    management.endpoint.health.show-details=always
    
    # Database configuration
    spring.datasource.url=${DB_URL}
    spring.datasource.username=${DB_USERNAME}
    spring.datasource.password=${DB_PASSWORD}
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.generate-ddl=true
    spring.jpa.show-sql=true
    spring.sql.init.platform=postgres
    
    spring.jpa.properties.hibernate.default_schema=accounts_schema
    spring.jpa.hibernate.ddl-auto=none
    spring.jpa.properties.hibernate.format_sql=true
    spring.sql.init.mode=always
    
    # OAuth2 Client Configuration
    auth.server.url=http://auth-server-service:9000
    auth.client.id=${OAUTH2_CLIENT_ID}
    auth.client.secret=${OAUTH2_CLIENT_SECRET}
    
    spring.security.oauth2.client.registration.auth-server.client-id=${OAUTH2_CLIENT_ID}
    spring.security.oauth2.client.registration.auth-server.client-secret=${OAUTH2_CLIENT_SECRET}
    spring.security.oauth2.client.registration.auth-server.authorization-grant-type=client_credentials
    spring.security.oauth2.client.registration.auth-server.scope=read,write
    
    spring.security.oauth2.client.provider.auth-server.token-uri=http://auth-server-service:9000/oauth2/token
    
    server.servlet.session.cookie.same-site=lax
    server.servlet.session.cookie.path=/

