apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-server-config
  namespace: simplebank
data:
  application.properties: |
    server.port=9000

    spring.application.name=auth-server

    authserver.issuer=http://localhost:9000
    authserver.redirect=http://localhost:8080

    # Actuator configuration
    management.endpoints.web.exposure.include=health,info
    management.endpoint.health.show-details=always

    # OAuth2 Client Configuration
    auth.server.url=http://localhost:9000
    auth.client.id=accounts-client
    auth.client.secret=accounts-secret

    spring.security.oauth2.client.registration.auth-server.client-id=${auth.client.id}
    spring.security.oauth2.client.registration.auth-server.client-secret=${auth.client.secret}
    spring.security.oauth2.client.registration.auth-server.authorization-grant-type=client_credentials
    spring.security.oauth2.client.registration.auth-server.scope=read,write

    spring.security.oauth2.client.provider.auth-server.token-uri=${auth.server.url}/oauth2/token

    server.servlet.session.cookie.same-site=lax
    server.servlet.session.cookie.path=/