apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-server.fullname" . }}-secret
  labels:
    {{- include "auth-server.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ .Values.database.password | b64enc }}
