apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: simplebank
data:
  # Service URLs
  auth-server-url: "http://auth-server-service:9000"
  gateway-url: "http://gateway-service:8081"
  
  # Database settings
  db-host: "postgresql-service"
  db-port: "5432"
  db-name: "simplebank_db"
  
  # Common Spring Boot settings
  spring-profiles-active: "kubernetes"

