---
apiVersion: v1
kind: Secret
metadata:
  name: accounts-oauth2-secret
  namespace: simplebank
type: Opaque
data:
  # accounts-client
  client-id: YWNjb3VudHMtY2xpZW50
  # accounts-secret
  client-secret: YWNjb3VudHMtc2VjcmV0

---
apiVersion: v1
kind: Secret
metadata:
  name: blocker-oauth2-secret
  namespace: simplebank
type: Opaque
data:
  # blocker-client
  client-id: YmxvY2tlci1jbGllbnQ=
  # blocker-secret
  client-secret: YmxvY2tlci1zZWNyZXQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: cash-oauth2-secret
  namespace: simplebank
type: Opaque
data:
  # cash-client
  client-id: Y2FzaC1jbGllbnQ=
  # cash-secret
  client-secret: Y2FzaC1zZWNyZXQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: exchange-oauth2-secret
  namespace: simplebank
type: Opaque
data:
  # exchange-client
  client-id: ZXhjaGFuZ2UtY2xpZW50
  # exchange-secret
  client-secret: ZXhjaGFuZ2Utc2VjcmV0

---
apiVersion: v1
kind: Secret
metadata:
  name: exchange-generator-oauth2-secret
  namespace: simplebank
type: Opaque
data:
  # exchange-generator-client
  client-id: ZXhjaGFuZ2UtZ2VuZXJhdG9yLWNsaWVudA==
  # exchange-generator-secret
  client-secret: ZXhjaGFuZ2UtZ2VuZXJhdG9yLXNlY3JldA==

---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-oauth2-secret
  namespace: simplebank
type: Opaque
data:
  # gateway-client
  client-id: Z2F0ZXdheS1jbGllbnQ=
  # gateway-secret
  client-secret: Z2F0ZXdheS1zZWNyZXQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: notifications-oauth2-secret
  namespace: simplebank
type: Opaque
data:
  # notifications-client
  client-id: bm90aWZpY2F0aW9ucy1jbGllbnQ=
  # notifications-secret
  client-secret: bm90aWZpY2F0aW9ucy1zZWNyZXQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: transfer-oauth2-secret
  namespace: simplebank
type: Opaque
data:
  # transfer-client
  client-id: dHJhbnNmZXItY2xpZW50
  # transfer-secret
  client-secret: dHJhbnNmZXItc2VjcmV0

