apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cash.fullname" . }}-db-secret
  labels:
    {{- include "cash.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.config.database.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cash.fullname" . }}-oauth-secret
  labels:
    {{- include "cash.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ .Values.config.auth.server.client.secret | b64enc }}
