spring.application.name=exchange

# OAuth2 Client Configuration
spring.security.oauth2.client.registration.auth-server.client-id=${AUTH_CLIENT_ID:exchange-client}
spring.security.oauth2.client.registration.auth-server.client-secret=${AUTH_CLIENT_SECRET:exchange-secret}
spring.security.oauth2.client.registration.auth-server.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.auth-server.scope=read,write

spring.security.oauth2.client.provider.auth-server.token-uri=${AUTH_SERVER_URL:http://localhost:9000}/oauth2/token

auth.server.url=http://localhost:9000