apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exchange.fullname" . }}-secret
  labels:
    {{- include "exchange.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ .Values.database.password | b64enc }}
  oauth2-client-secret: {{ .Values.oauth2.clientSecret | b64enc }}
